name: Docker Compose SSH Deployment
description: Deploy a repository with docker-compose via SSH to a remote host.
branding:
  icon: anchor
  color: blue
inputs:
  ssh_private_key:
    description: The SSH private key used for logging into remote system.
    required: true
  ssh_host:
    description: The remote host name or IP address.
    required: true
  ssh_port:
    description: The remote port number.
    default: '22'
  ssh_user:
    description: The remote username.
    default: 'docker-deploy'
  docker_compose_prefix:
    description: The prefix to add to the deployed containers. <prefix>:x in docker hub.
  docker_compose_filename:
    description: The docker-compose file name.
    default: docker-compose.yaml
  docker_compose_filename_production:
    description: The docker-compose file name that merges with the base filename in production.
    default: docker-compose.prod.yaml
  dockerhub_username:
    description: Docker Hub username used for login.
  dockerhub_password:
    description: Docker Hub password used for login.
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_FILENAME_PRODUCTION: ${{ inputs.docker_compose_filename_production }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    DOCKERHUB_USERNAME: ${{ inputs.dockerhub_username }}
    DOCKERHUB_PASSWORD: ${{ inputs.dockerhub_password }}
